#!/usr/bin/env python3
"""CLI entrypoint for the social publisher (script 2 of 2).

Reads the per-product JSON + source images produced by ``generate_prompts.py``
and, for each creative concept, generates a marketing image with Grok and writes
a ready-to-paste social post text file next to it.

Examples
--------
    # Default: read ./output, write ./social
    python generate_social.py

    # Custom input folder + higher-quality model + 2 variations each
    python generate_social.py --input output --out-dir social --quality --variations 2

    # Only one concept, for one product
    python generate_social.py --concept "Lifestyle Image"
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from product_prompts.config import Settings
from product_prompts.utils import configure_logging, get_logger

from social_publisher.pipeline import SocialPublisher

log = get_logger("social.cli")


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate marketing images + paste-ready social text from product JSON."
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=None,
        help="Folder containing product JSON + images (default: output/).",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("social"),
        help="Folder to write generated images + post text (default: social/).",
    )
    parser.add_argument(
        "--backend",
        default="grok",
        choices=["grok"],
        help="Image generation backend (default: grok).",
    )
    parser.add_argument(
        "--quality",
        action="store_true",
        help="Use the higher-quality (more expensive) image model.",
    )
    parser.add_argument(
        "--variations",
        type=int,
        default=1,
        help="Number of image variations per concept (default: 1).",
    )
    parser.add_argument(
        "--concept",
        action="append",
        default=None,
        help="Only generate for this concept name (repeatable).",
    )
    parser.add_argument(
        "--max-references",
        type=int,
        default=3,
        help="Real product images to use as reference for fidelity (1-3, default: 3). "
        "Marketing images are only generated by editing these photos; products "
        "with no reference image are skipped.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Regenerate even if outputs already exist.",
    )
    parser.add_argument("--verbose", action="store_true", help="Enable debug logging.")
    return parser


def main(argv=None) -> int:
    args = build_arg_parser().parse_args(argv)
    configure_logging(args.verbose)

    settings = Settings.load()
    input_dir = args.input if args.input else settings.output_dir

    if not settings.grok_api_key:
        log.error("GROK_API_KEY is not set in the environment/.env; cannot generate images.")
        return 2

    publisher = SocialPublisher(
        settings,
        backend_name=args.backend,
        quality=args.quality,
        variations=args.variations,
        concept_filter=args.concept,
        overwrite=args.overwrite,
        max_references=args.max_references,
    )
    produced = publisher.run(input_dir, args.out_dir)

    if not produced:
        log.error("Nothing was generated.")
        return 1
    log.info("Done. Wrote %d file(s) to %s", len(produced), args.out_dir)
    return 0


if __name__ == "__main__":
    sys.exit(main())
