#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# service.sh — Production service manager for AI Blog Generator
#
# Usage:  ./service.sh {start|stop|restart|status}
#
# Manages four processes:
#   • React app    — Shopify/React frontend (port 3000, localhost only)
#   • main.py      — FastAPI / uvicorn backend (port 4000, localhost only)
#   • scheduler.py — Autonomous blog post scheduler
#   • caddy        — TLS reverse proxy (port 8443 → React app)
#
# TLS mode (auto-detected from .env):
#   CERT_FILE + KEY_FILE present  →  explicit cert mode (certbot-managed certs)
#   otherwise                     →  Caddy auto-HTTPS via ACME HTTP-01
#                                    Requires port 80 open in AWS security group
#                                    and DNS pointing at this server.
#                                    Cloudflare must be in "Full" SSL mode.
#
# AWS security group:  open 80 (ACME) and 8443 (Cloudflare inbound) inbound.
# Cloudflare:          "Full" SSL mode, proxy enabled on your domain.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Paths ────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$SCRIPT_DIR"
WORKSPACE_DIR="$(cd "$APP_DIR/.." && pwd)"
FRONTEND_DIR="${FRONTEND_DIR:-$WORKSPACE_DIR/ai-blog-generator-app}"

RUN_DIR="$APP_DIR/run"
LOG_DIR="$APP_DIR/logs"
mkdir -p "$RUN_DIR" "$LOG_DIR"

MAIN_PID="$RUN_DIR/main.pid"
FRONTEND_PID="$RUN_DIR/frontend.pid"
SCHED_PID="$RUN_DIR/scheduler.pid"
CADDY_PID="$RUN_DIR/caddy.pid"

MAIN_LOG="$LOG_DIR/main.log"
FRONTEND_LOG="$LOG_DIR/frontend.log"
SCHED_LOG="$LOG_DIR/scheduler.log"
CADDY_LOG="$LOG_DIR/caddy.log"
CADDY_ACCESS_LOG="$LOG_DIR/caddy-access.log"

GENERATED_CADDYFILE="$RUN_DIR/Caddyfile"

# ── Load .env files ───────────────────────────────────────────────────────────

# Load the shared workspace env first, then service-specific env files so more
# local values can override shared defaults.
ENV_FILES=()
for _candidate in "$WORKSPACE_DIR/.env" "$APP_DIR/.env" "$FRONTEND_DIR/.env"; do
    if [[ -f "$_candidate" ]]; then
        ENV_FILES+=("$(realpath "$_candidate")")
    fi
done

if (( ${#ENV_FILES[@]} > 0 )); then
    set -a
    for ENV_FILE in "${ENV_FILES[@]}"; do
        # shellcheck source=/dev/null
        source "$ENV_FILE"
    done
    set +a
fi

if [[ -z "${DOMAIN:-}" && -n "${SHOPIFY_REACT_APP_URL:-}" ]]; then
    DOMAIN="${SHOPIFY_REACT_APP_URL#*://}"
    DOMAIN="${DOMAIN%%/*}"
    DOMAIN="${DOMAIN%%:*}"
fi

# ── Environment detection ─────────────────────────────────────────────────────
# macOS  → development  (no Caddy, frontend via `npm run dev`)
# Linux  → production   (Caddy TLS proxy, frontend via built `npm run start`)
# Override at any time with:  DEV_MODE=true ./service.sh start
_OS="$(uname -s)"
if [[ "${DEV_MODE:-}" == "true" || ( "${DEV_MODE:-}" != "false" && "$_OS" == "Darwin" ) ]]; then
    IS_DEV=true
    ENV_LABEL="development (macOS/localhost)"
else
    IS_DEV=false
    ENV_LABEL="production (${DOMAIN:-revenuemindproai.com})"
fi

# ── Resolve executables ───────────────────────────────────────────────────────

# Use virtualenv python if present, else system python3
if [[ -x "$APP_DIR/.venv/bin/python" ]]; then
    PYTHON="$APP_DIR/.venv/bin/python"
elif [[ -x "$APP_DIR/venv/bin/python" ]]; then
    PYTHON="$APP_DIR/venv/bin/python"
else
    PYTHON="${PYTHON:-python3}"
fi

CADDY="${CADDY:-caddy}"
NPM="${NPM:-npm}"
FRONTEND_PORT="${FRONTEND_PORT:-3000}"
PYTHON_BACKEND_PORT="${PYTHON_BACKEND_PORT:-4000}"

if [[ "$IS_DEV" != "true" ]] && ! command -v "$CADDY" &>/dev/null; then
    echo "ERROR: caddy not found. Install via: brew install caddy  or  apt install caddy" >&2
    exit 1
fi

if ! command -v "$NPM" &>/dev/null; then
    echo "ERROR: npm not found. Install Node.js 20+ and npm before starting the Shopify frontend." >&2
    exit 1
fi

# ── Caddy config generation ───────────────────────────────────────────────────

_write_caddyfile() {
    local domain="${DOMAIN:-localhost}"
    local cert="${CERT_FILE:-}"
    local key="${KEY_FILE:-}"

    if [[ -n "$cert" && -r "$cert" && -n "$key" && -r "$key" ]]; then
        # ── Explicit cert mode (certbot / manual) ──────────────────────────
        echo "  Caddy TLS mode: explicit cert ($cert)"
        cat > "$GENERATED_CADDYFILE" <<CADDYFILE
# Auto-generated by service.sh — explicit cert mode
{
    auto_https disable_redirects
    servers {
        protocols h1 h2
    }
}

${domain}:8443 {
    tls ${cert} ${key}

    reverse_proxy localhost:${FRONTEND_PORT} {
        header_up X-Real-IP {remote_host}
        header_up X-Forwarded-Proto https
    }

    encode gzip

    log {
        output file ${CADDY_ACCESS_LOG}
        format console
    }
}
CADDYFILE
    else
        # ── Caddy auto-HTTPS mode ──────────────────────────────────────────
        # Caddy manages the cert via ACME HTTP-01.
        # Port 80 must be reachable from the internet for the ACME challenge.
        # Set https_port to 8443 so Caddy listens there instead of 443.
        echo "  Caddy TLS mode: auto-HTTPS (ACME) on port 8443"
        echo "  NOTE: port 80 must be open in your AWS security group for cert issuance."
        cat > "$GENERATED_CADDYFILE" <<CADDYFILE
# Auto-generated by service.sh — Caddy auto-HTTPS mode
{
    # Use 8443 for HTTPS (Cloudflare inbound) and 80 for ACME HTTP-01 challenges
    http_port  80
    https_port 8443
    servers {
        protocols h1 h2
    }
}

${domain} {
    reverse_proxy localhost:${FRONTEND_PORT} {
        header_up X-Real-IP {remote_host}
        header_up X-Forwarded-Proto https
    }

    encode gzip

    log {
        output file ${CADDY_ACCESS_LOG}
        format console
    }
}
CADDYFILE
    fi
}

# ── PID helpers ───────────────────────────────────────────────────────────────

_is_running() {
    local pid_file="$1"
    if [[ -f "$pid_file" ]]; then
        local pid
        pid=$(<"$pid_file")
        if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
            return 0
        fi
        rm -f "$pid_file"
    fi
    return 1
}

_stop_pid() {
    local name="$1"
    local pid_file="$2"
    if _is_running "$pid_file"; then
        local pid
        pid=$(<"$pid_file")
        echo "  Stopping $name (pid=$pid)..."
        kill "$pid" 2>/dev/null || true
        local i=0
        while kill -0 "$pid" 2>/dev/null && (( i < 15 )); do
            sleep 1
            (( i++ )) || true
        done
        if kill -0 "$pid" 2>/dev/null; then
            echo "  Force-killing $name..."
            kill -9 "$pid" 2>/dev/null || true
        fi
        rm -f "$pid_file"
        echo "  $name stopped."
    else
        echo "  $name is not running."
    fi
}

# ── Start helpers ─────────────────────────────────────────────────────────────

_start_frontend() {
    if _is_running "$FRONTEND_PID"; then
        echo "  React app already running (pid=$(cat "$FRONTEND_PID"))"
        return
    fi
    if [[ ! -d "$FRONTEND_DIR" ]]; then
        echo "ERROR: React app directory not found: $FRONTEND_DIR" >&2
        exit 1
    fi

    if [[ "$IS_DEV" == "true" ]]; then
        # ── Dev mode: Shopify CLI tunnel (npm run dev) ─────────────────────
        # The CLI creates a public tunnel URL and handles OAuth redirects.
        # Check the frontend log for the tunnel URL after starting.
        echo "  Starting React app (dev — shopify app dev)..."
        cd "$FRONTEND_DIR"
        PORT="$FRONTEND_PORT" \
        AI_BLOG_BACKEND_URL="http://127.0.0.1:${PYTHON_BACKEND_PORT}" \
        nohup "$NPM" run dev >> "$FRONTEND_LOG" 2>&1 &
        local pid=$!
        disown "$pid"
        echo "$pid" > "$FRONTEND_PID"
        echo "  React app started (pid=$pid) → $FRONTEND_LOG"
        echo "  Tip: tail -f $FRONTEND_LOG  to see the Shopify tunnel URL"
    else
        # ── Prod mode: pre-built app via react-router-serve ────────────────
        if [[ ! -f "$FRONTEND_DIR/build/server/index.js" ]]; then
            echo "ERROR: React app build not found at $FRONTEND_DIR/build/server/index.js" >&2
            echo "Run this once: cd $FRONTEND_DIR && npm install && npm run build" >&2
            exit 1
        fi
        echo "  Starting React app (production — react-router-serve)..."
        cd "$FRONTEND_DIR"
        PORT="$FRONTEND_PORT" \
        AI_BLOG_BACKEND_URL="${AI_BLOG_BACKEND_URL:-http://127.0.0.1:${PYTHON_BACKEND_PORT}}" \
        SHOPIFY_REACT_APP_URL="${SHOPIFY_REACT_APP_URL:-https://${DOMAIN:-localhost}:8443}" \
        nohup "$NPM" run start >> "$FRONTEND_LOG" 2>&1 &
        local pid=$!
        disown "$pid"
        echo "$pid" > "$FRONTEND_PID"
        echo "  React app started (pid=$pid, port=$FRONTEND_PORT) → $FRONTEND_LOG"
    fi
}

_start_main() {
    if _is_running "$MAIN_PID"; then
        echo "  main.py already running (pid=$(cat "$MAIN_PID"))"
        return
    fi
    echo "  Starting main.py..."
    cd "$APP_DIR"
    nohup "$PYTHON" main.py >> "$MAIN_LOG" 2>&1 &
    local pid=$!
    disown "$pid"
    echo "$pid" > "$MAIN_PID"
    echo "  main.py started (pid=$pid) → $MAIN_LOG"
}

_start_scheduler() {
    if _is_running "$SCHED_PID"; then
        echo "  scheduler.py already running (pid=$(cat "$SCHED_PID"))"
        return
    fi
    echo "  Starting scheduler.py..."
    cd "$APP_DIR"
    nohup "$PYTHON" scheduler.py >> "$SCHED_LOG" 2>&1 &
    local pid=$!
    disown "$pid"
    echo "$pid" > "$SCHED_PID"
    echo "  scheduler.py started (pid=$pid) → $SCHED_LOG"
}

_start_caddy() {
    if _is_running "$CADDY_PID"; then
        echo "  Caddy already running (pid=$(cat "$CADDY_PID"))"
        return
    fi
    echo "  Starting Caddy..."
    _write_caddyfile
    nohup "$CADDY" run --config "$GENERATED_CADDYFILE" --adapter caddyfile >> "$CADDY_LOG" 2>&1 &
    local pid=$!
    disown "$pid"
    echo "$pid" > "$CADDY_PID"
    echo "  Caddy started (pid=$pid) → $CADDY_LOG"
}

# ── Commands ──────────────────────────────────────────────────────────────────

do_start() {
    echo "Starting services [${ENV_LABEL}]..."
    _start_main
    _start_scheduler
    _start_frontend
    if [[ "$IS_DEV" != "true" ]]; then
        _start_caddy
    fi
    echo "Done."
}

do_stop() {
    echo "Stopping services [${ENV_LABEL}]..."
    if [[ "$IS_DEV" != "true" ]]; then
        _stop_pid "Caddy"    "$CADDY_PID"
    fi
    _stop_pid "React app"    "$FRONTEND_PID"
    _stop_pid "scheduler.py" "$SCHED_PID"
    _stop_pid "main.py"      "$MAIN_PID"
    echo "Done."
}

do_restart() {
    do_stop
    sleep 1
    do_start
}

do_status() {
    echo "Service status [${ENV_LABEL}]:"
    local all_ok=true
    local services=("main.py:$MAIN_PID" "scheduler.py:$SCHED_PID" "React app:$FRONTEND_PID")
    if [[ "$IS_DEV" != "true" ]]; then
        services+=("Caddy:$CADDY_PID")
    fi
    for entry in "${services[@]}"; do
        local name="${entry%%:*}"
        local pid_file="${entry##*:}"
        if _is_running "$pid_file"; then
            local pid
            pid=$(<"$pid_file")
            printf "  %-14s  \033[32mRUNNING\033[0m  (pid=%s)\n" "$name" "$pid"
        else
            printf "  %-14s  \033[31mSTOPPED\033[0m\n" "$name"
            all_ok=false
        fi
    done
    $all_ok && exit 0 || exit 1
}

# ── Entry point ───────────────────────────────────────────────────────────────

case "${1:-}" in
    start)   do_start   ;;
    stop)    do_stop    ;;
    restart) do_restart ;;
    status)  do_status  ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac
