"""Social publisher pipeline: product JSON -> generated images + post text files."""

from __future__ import annotations

import re
from pathlib import Path
from typing import List, Optional

from services.landing_pages.product_prompts.config import Settings
from services.landing_pages.product_prompts.utils import build_session, get_logger, slugify

from .caption import build_post_text
from .image_backends import get_image_backend
from .loader import iter_products

log = get_logger("social.pipeline")


class SocialPublisher:
    def __init__(
        self,
        settings: Settings,
        backend_name: str = "grok",
        quality: bool = False,
        variations: int = 1,
        concept_filter: Optional[List[str]] = None,
        overwrite: bool = False,
        max_references: int = 3,
    ) -> None:
        self.settings = settings
        self.session = build_session(settings.user_agent, settings.max_retries)
        self.backend = get_image_backend(
            backend_name, settings, self.session, quality=quality
        )
        self.variations = max(1, variations)
        self.concept_filter = (
            {c.strip().lower() for c in concept_filter} if concept_filter else None
        )
        self.overwrite = overwrite
        # Marketing images are only generated by editing real product photos, so
        # at least one reference is always required (1-3).
        self.max_references = max(1, min(max_references, 3))
        log.info(
            "Publisher ready: backend=%s model=%s variations=%d references=%d",
            self.backend.name,
            getattr(self.backend, "model", "?"),
            self.variations,
            self.max_references,
        )

    # ------------------------------------------------------------------
    def run(self, input_dir: Path, output_dir: Path) -> List[Path]:
        output_dir.mkdir(parents=True, exist_ok=True)
        produced: List[Path] = []
        for path, data in iter_products(input_dir):
            log.info("Publishing from %s", path.name)
            produced.extend(self._process_product(path, data, output_dir))
        return produced

    # ------------------------------------------------------------------
    def _process_product(self, path: Path, data: dict, output_dir: Path) -> List[Path]:
        handle = slugify(path.stem)
        product = data.get("product", {})
        persona = data.get("persona", {})
        campaign = data.get("campaign", {})
        concepts = data.get("creative_concepts", [])

        # Marketing images are only generated by editing real product photos.
        # Without a reference image there is nothing to anchor the product to,
        # so we skip the product entirely.
        references = self._load_references(data, path.parent)
        if not references:
            log.warning(
                "No reference images found for %s; skipping (marketing images "
                "require at least one real product photo).",
                handle,
            )
            return []
        log.info("Using %d reference image(s) for %s", len(references), handle)

        produced: List[Path] = []
        for concept in concepts:
            name = concept.get("concept", "concept")
            if not self._concept_matches_filter(name):
                continue
            try:
                produced.extend(
                    self._process_concept(
                        handle, product, persona, campaign, concept, references, output_dir
                    )
                )
            except Exception as exc:  # noqa: BLE001 - one bad concept shouldn't stop the run
                log.error("Failed concept '%s' for %s: %s", name, handle, exc)
        return produced

    def _concept_matches_filter(self, name: str) -> bool:
        if not self.concept_filter:
            return True

        # The UI identifies an image by its filename slug, while generated JSON
        # stores the human-readable concept name. Accept either representation,
        # including historical variation suffixes such as ``_v1``.
        candidates = {name.strip().lower(), slugify(name)}
        requested = {
            re.sub(r"_v\d+$", "", value.strip().lower())
            for value in self.concept_filter
        }
        return bool(candidates & requested)

    def _load_references(self, data: dict, input_dir: Path) -> List[bytes]:
        """Read up to ``max_references`` product images from disk as bytes.

        Paths come from the JSON ``assets`` (main image first). Each is resolved
        as-is and, failing that, by filename relative to the JSON's folder, so
        the output directory can be moved without breaking references.
        """
        candidates: List[str] = []
        main_image = data.get("main_image")
        if main_image:
            candidates.append(main_image)
        for asset in data.get("assets", []):
            local = asset.get("local_path")
            if local and local not in candidates:
                candidates.append(local)

        references: List[bytes] = []
        seen: set = set()
        for candidate in candidates:
            if len(references) >= self.max_references:
                break
            resolved = self._resolve_path(candidate, input_dir)
            if resolved is None or resolved in seen:
                continue
            seen.add(resolved)
            try:
                references.append(resolved.read_bytes())
            except OSError as exc:
                log.warning("Could not read reference image %s: %s", resolved, exc)
        return references

    @staticmethod
    def _resolve_path(candidate: str, input_dir: Path) -> Optional[Path]:
        direct = Path(candidate)
        if direct.exists():
            return direct
        fallback = input_dir / direct.name
        if fallback.exists():
            return fallback
        return None

    def _process_concept(
        self, handle, product, persona, campaign, concept, references, output_dir
    ) -> List[Path]:
        name = concept.get("concept", "concept")
        slug = slugify(name)
        prompt = (concept.get("image_prompt") or "").strip()
        if not prompt:
            log.warning("Concept '%s' has no image_prompt; skipping.", name)
            return []

        base = f"{handle}__{slug}"
        suffixes = (
            [""] if self.variations == 1 else [f"_v{i}" for i in range(1, self.variations + 1)]
        )

        produced: List[Path] = []
        slots_needing_image: List[str] = []
        # First pass: keep existing images, cheaply recreate any missing text file.
        for suffix in suffixes:
            image_path = self._find_image(output_dir, base, suffix)
            text_path = output_dir / f"{base}{suffix}.txt"
            if self.overwrite or image_path is None:
                slots_needing_image.append(suffix)
                continue
            produced.append(image_path)
            if not text_path.exists():
                self._write_text(text_path, product, campaign, concept)
                log.info("Recreated missing text file %s", text_path.name)
            produced.append(text_path)

        if not slots_needing_image:
            log.info("Skipping '%s' (images already present).", base)
            return produced

        # Second pass: (re)generate only the images that are actually missing.
        log.info(
            "Generating %d image(s) for '%s — %s'",
            len(slots_needing_image),
            handle,
            name,
        )
        images = self.backend.generate(
            prompt,
            negative_prompt=concept.get("negative_prompt", ""),
            n=len(slots_needing_image),
            reference_images=references,
        )

        for suffix, image in zip(slots_needing_image, images):
            image_name = f"{base}{suffix}{image.extension}"
            image_path = output_dir / image_name
            image_path.write_bytes(image.data)
            self._remove_other_image_formats(output_dir, base, suffix, image_path)
            produced.append(image_path)

            text_path = output_dir / f"{base}{suffix}.txt"
            self._write_text(text_path, product, campaign, concept)
            produced.append(text_path)
            log.info("Wrote %s + %s", image_name, text_path.name)
        return produced

    @staticmethod
    def _find_image(output_dir: Path, base: str, suffix: str) -> Optional[Path]:
        for ext in (".jpg", ".jpeg", ".png", ".webp"):
            candidate = output_dir / f"{base}{suffix}{ext}"
            if candidate.exists():
                return candidate
        return None

    @staticmethod
    def _remove_other_image_formats(
        output_dir: Path, base: str, suffix: str, keep: Path
    ) -> None:
        for ext in (".jpg", ".jpeg", ".png", ".webp"):
            candidate = output_dir / f"{base}{suffix}{ext}"
            if candidate != keep and candidate.exists():
                candidate.unlink()

    @staticmethod
    def _write_text(path: Path, product: dict, campaign: dict, concept: dict) -> None:
        path.write_text(build_post_text(product, campaign, concept), encoding="utf-8")
